version: 2.1    
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker build --build-arg version=0.${CIRCLE_BUILD_NUM} -t form2mattermost:0.${CIRCLE_BUILD_NUM} .
