version: 2.1    
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment: 
      BUILDTAG: 0
    steps:
      - checkout
      - run: BUILDTAG=$CIRCLE_BUILD_NUM && echo "docker build --build-arg version=0.${BUILDTAG} -t form2mattermost:0.${CIRCLE_BUILD_NUM} ."
