version: 2.1    
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment: 
      BUILDTAG: 0
    steps:
      - checkout
      - run:
          name: Define BUILD_TAG and build image
          command: |
            echo 'export BUILDTAG=$CIRCLE_BUILD_NUM' >> $BASH_ENV
            && source $BASH_ENV
            && env | grep BUILD_TAG
            && env | grep CIRCLE_BUILD_NUM
            && docker build --build-arg version=0.${BUILD_TAG} -t form2mattermost:0.$BUILD_TAG .
