version: 2.1    
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      GITREV: << pipeline.git.revision >>
    steps:
      - checkout
      - run: GITREV="${GITREV:0:6}"
      - run: docker build --build-arg version=$GITREV -t form2mattermost:$GITREV .
